name: cmesig
dependencies:
  - python==3.7.6
  - numpy==1.19.1
  - matplotlib==3.3.1
  - ipython==7.11.1
  - pip==19.3.1
  - numba==0.50.1
  - scipy==1.5.2
  - scikit-learn==0.23.2
  - scikit-image==0.17.1
  - pandas==1.1.0
  - seaborn==0.10.1
  - astropy==4.0
  - h5py==2.10.0



